[versions]
minecraft = "1.21.4"
yarn-mappings = "1.21.4+build.8"
fabric-loader = "0.18.4"
fabric-api = "0.119.4+1.21.4"
fabric-loom = "1.9-SNAPSHOT"

kotlin = "2.1.0"
compose = "1.7.3"
fabric-kotlin = "1.13.0+kotlin.2.1.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
